name: Push github-actions-exporter container image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: New tag of the github-actions-exporter container image
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags="-X 'main.version=$VERSION'"  -o bin/app
      env:
        VERSION: ${{ github.event.inputs.tag }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the image and push it
      run: |
        docker build . -t ${{ env.image-name }}:${{ env.image-tag }}
        docker push ${{ env.image-name }}:${{ env.image-tag }}
      env:
        image-name: ghcr.io/${{ github.repository }}
        image-tag: ${{ github.event.inputs.tag }}
